[package]
name = "calc-language"
version = "0.1.0"
authors = ["Nuno Barreto <nbarreto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
pest = "2.1"
pest_derive = "2.1"
